server:
  port: 80
spring:
  application:
    name: user-consumer
eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:10086/eureka